### PR TITLE
Changelog for v1.4.0

### PR DESCRIPTION
**Pull request by michaelbausor**
- Add support for insecure credentials (#208)

### CODE REVIEW

**Comment by michaelbausor** [comment]
cc @tmatsuo @dwsupplee @jdpedrie @bshaffer

**Comment by michaelbausor** [comment]
Thanks @tmatsuo! I don't have merge access on this repo - if possible, could you merge this and cut the release? Or else give me merge access :-)

**Comment by tmatsuo** [comment]
@michaelbausor Released! https://github.com/googleapis/google-auth-library-php/releases/tag/v1.4.0

**Comment by michaelbausor** [comment]
Awesome, thank you!

**Pull request merged**
