### PR TITLE
feat: Allow caching the result of ADC::onGce separately

### PR DESCRIPTION
**Pull request by MrMage**
Motivation: Lets us cache the result of ADC::onGce without returning a `FetchAuthTokenCache`, as that might lead to nested caches.

Also see https://github.com/googleapis/google-cloud-php/pull/3959 and https://github.com/googleapis/gax-php/pull/318.

### CODE REVIEW

**Comment by bshaffer** [comment]
Thank you for submitting this PR!

This change seems okay, but I don't quite understand why it's useful. Can you provide an instance where the result would be nested caches, or provide the use-case for why someone would need to keep those caches separate?

**Comment by MrMage** [comment]
Sorry, I should have provided more details! Currently, e.g. `RequestWrapperTrait` in the Google Cloud SDK passes a `null` auth cache to `ADC::getCredentials`, in order to avoid nesting two `FetchAuthTokenCache` (see https://github.com/googleapis/google-cloud-php/pull/3959). However, this means that `onGce` will also be called with a `null` auth cache, i.e. that request needs to be sent at least once on every request to my web app. This adds ~1ms of avoidable latency to my response times.

To allow caching the result of `onGce` _without_ nesting `FetchAuthTokenCache`, this PR adds a separate cache argument that only gets forwarded to `onGce`.

**Comment by bshaffer** [comment]
I could be missing something, but it seems like we could simply avoid nested `FetchAuthTokenCache` by checking to make sure the `$cache` object is not `FetchAuthTokenCache` before wrapping it.

If this is sufficient, it seems like a better solution to me.

**Comment by MrMage** [comment]
> I could be missing something, but it seems like we could simply avoid nested `FetchAuthTokenCache` by checking to make sure the `$cache` object is not `FetchAuthTokenCache` before wrapping it.
> 
> If this is sufficient, it seems like a better solution to me.

That indeed sounds like a better solution and updated https://github.com/googleapis/google-cloud-php/pull/3959 accordingly. Please have a look and let me know what you think :-)

**Comment by MrMage** [comment]
Made obsolete by https://github.com/googleapis/google-cloud-php/pull/3959.

**Pull request closed without merging**
