### PR TITLE
Describe the arrays returned by fetchAuthToken

### PR DESCRIPTION
**Pull request by dwsupplee**
Closes: https://github.com/googleapis/google-auth-library-php/issues/71

/cc @bshaffer

### CODE REVIEW

**Comment by dwsupplee** [comment]
Well, I'm at a bit of a loss as to why documentation updates are causing the tests to fail on travis. 😭

**Comment by dwsupplee** [comment]
Re-ran master and the same failures popped up. Looking in to it.

**Comment by bshaffer** [comment]
this repo done gone stale :-(

**Comment by dwsupplee** [comment]
Travis looks to be running on GCE, which is causing some GCE related tests to fail. Not sure why these were passing before yet..

**Comment by dwsupplee** [comment]
Tests are fixed. PTAL

**Pull request merged**
